# Chapter 12 - Introduction to Modeling Libraries in Python

# 12.1 Interfacing Between Pandas & Model Code

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [3]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [4]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [5]:
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [6]:
df3 = data.copy()

In [7]:
df3['strings'] = ['a', 'b', 'c', 'd', 'e']
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [8]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [9]:
model_cols = ['x0', 'x1']

In [10]:
data.loc[:, model_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [11]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                 categories=['a', 'b'])
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [12]:
dummies = pd.get_dummies(data.category, prefix='category')

In [13]:
data_with_dummies = data.drop('category', axis=1).join(dummies)
data_with_dummies

x0    x1    y  category_a  category_b
0   1  0.01 -1.5           1           0
1   2 -0.01  0.0           0           1
2   3  0.25  3.6           1           0
3   4 -4.10  1.3           1           0
4   5  0.00 -2.0           0           1

# 12.2 Creating Model Descriptions with Patsy

In [82]:
import statsmodels 
import patsy

##### Patsy Formula

In [161]:
# y ~ x0 + x1

In [16]:
data = pd.DataFrame({
    'x0':[1, 2, 3, 4, 5],
    'x1':[0.01, -0.01, 0.25, -4.1, 0.],
    'x2':[-1.5, 0., 3.6, 1.3, -2]})

In [17]:
data

x0    x1   x2
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [63]:
# y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [47]:
#y

In [49]:
#X 

In [50]:
#np.asarray(y)

In [51]:
#np.asarray(X)

In [52]:
# patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

In [54]:
# coef, resid, _, _ = np.linalg.lstsq(X, y)

In [64]:
# coef

In [ ]:
# coef = pd.Series(coef.squeeze(), index=X.desing_info.column_names)
# coef

# Data Tranformation in Patsy Formulas

In [67]:
# y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)
# X

In [68]:
# y, X = aptsy.dmatrices('y ~ standarize(x0) + center(x1)', data)

In [69]:
# X

In [70]:
new_data = pd.DataFrame({
    'x0': [6, 7, 8, 9],
    'x1': [3.1, -0.5, 0, 2.3],
    'x2': [1, 2, 3, 4]})

In [72]:
# new_X = patsy.build_desing_matrices([X.desing_info], new_data)
# new_X

In [76]:
# y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)
# X

### Categorical Data & Patsy

In [77]:
data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1, 2, 3, 4, 5, 6, 7, 8],
    'v2':[-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]})

In [84]:
# y, X = patsy.dmatrices('v2 ~ key1', data)

In [85]:
# y, X = patsy.dmatrices('v2 ~ c(key2)', data)
# X

In [87]:
# data['key2'] = data['key2'],map({0: 'zero', 1: 'one'})
# data

In [88]:
# y, X = patsy.dmatrices('v2 ~ key1 + key2', data)
# X

In [89]:
# y, X = patsy('v2 ~ key1 + key2 + key1:key2', data)
# X

# 12.3 Introduction to statsmodels

In [91]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [92]:
rng = np.random.default_rng(seed=12345)

def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * rng.standard_normal(*size)

In [93]:
N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size = N)
beta = [0.1, 0.3, 0.5]

In [94]:
y = np.dot(X, beta) + eps

In [95]:
X[:5]

array([[-0.90050602, -0.18942958, -1.0278702 ],
       [ 0.79925205, -1.54598388, -0.32739708],
       [-0.55065483, -0.12025429,  0.32935899],
       [-0.16391555,  0.82403985,  0.20827485],
       [-0.04765129, -0.21314698, -0.04824364]])

In [96]:
y[:5]

array([-0.59952668, -0.58845445,  0.18563386, -0.00747657, -0.01537445])

In [97]:
X_model = sm.add_constant(X)

In [98]:
X_model[:5]

array([[ 1.        , -0.90050602, -0.18942958, -1.0278702 ],
       [ 1.        ,  0.79925205, -1.54598388, -0.32739708],
       [ 1.        , -0.55065483, -0.12025429,  0.32935899],
       [ 1.        , -0.16391555,  0.82403985,  0.20827485],
       [ 1.        , -0.04765129, -0.21314698, -0.04824364]])

In [99]:
model = sm.OLS(y, X)

In [100]:
results = model.fit()
results.params

array([0.06681503, 0.26803235, 0.45052319])

In [101]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.469
Model:                            OLS   Adj. R-squared (uncentered):              0.452
Method:                 Least Squares   F-statistic:                              28.51
Date:                Sat, 25 Feb 2023   Prob (F-statistic):                    2.66e-13
Time:                        14:05:27   Log-Likelihood:                         -25.611
No. Observations:                 100   AIC:                                      57.22
Df Residuals:                      97   BIC:                                      65.04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [106]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])
data['y'] = y

In [107]:
data[:5]

col0      col1      col2         y
0 -0.900506 -0.189430 -1.027870 -0.599527
1  0.799252 -1.545984 -0.327397 -0.588454
2 -0.550655 -0.120254  0.329359  0.185634
3 -0.163916  0.824040  0.208275 -0.007477
4 -0.047651 -0.213147 -0.048244 -0.015374

In [110]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()

In [112]:
results.params

Intercept   -0.020799
col0         0.065813
col1         0.268970
col2         0.449419
dtype: float64

In [113]:
results.tvalues

Intercept   -0.652501
col0         1.219768
col1         6.312369
col2         6.567428
dtype: float64

In [114]:
results.predict(data[:5])

0   -0.592959
1   -0.531160
2    0.058636
3    0.283658
4   -0.102947
dtype: float64

### Estimating Time Series Processes

In [115]:
init_x = 4

values = [init_x, init_x]
N = 1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [117]:
from statsmodels.tsa.ar_model import AutoReg

In [118]:
MAXLAGS = 5

In [119]:
model = AutoReg(values, MAXLAGS)

In [120]:
results = model.fit()

In [121]:
results.params

array([ 0.02346612,  0.8096828 , -0.42865278, -0.03336517,  0.04267874,
       -0.05671529])

# 12.4 Introduction to scikit-learn

In [122]:
train = pd.read_csv('datasets/titanic/train.csv')

In [123]:
test = pd.read_csv('datasets/titanic/test.csv')

In [124]:
train.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [125]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [126]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [127]:
impute_value = train['Age'].median()

In [128]:
train['Age'] = train['Age'].fillna(impute_value)

In [129]:
test['Age'] = test['Age'].fillna(impute_value)

In [134]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)

In [135]:
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [136]:
predictors = ['Pclass', 'IsFemale', 'Age']

In [137]:
X_train = train[predictors].to_numpy()

In [138]:
X_test = test[predictors].to_numpy()

In [139]:
y_train = train['Survived'].to_numpy()

In [140]:
X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [141]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [142]:
from sklearn.linear_model import LogisticRegression

In [143]:
model = LogisticRegression()

In [144]:
model.fit(X_train, y_train)

LogisticRegression()

In [145]:
y_predict = model.predict(X_test)

In [146]:
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [148]:
# (y_true == y_predict).mean()

In [149]:
from sklearn.linear_model import LogisticRegressionCV

In [150]:
model_cv = LogisticRegressionCV(Cs=10)

In [151]:
model_cv.fit(X_train, y_train)

LogisticRegressionCV()

In [152]:
from sklearn.model_selection import cross_val_score

In [153]:
model = LogisticRegression(C=10)

In [154]:
scores = cross_val_score(model, X_train, y_train, cv=4)
scores

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])