# Chapter 7 - Data Cleaning & Preparation

In [1]:
import numpy as np
import pandas as pd
import re

# 7.1 Handling Missing Data

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(["aarvark", np.nan, None, "avocado"])
string_data

0    aarvark
1        NaN
2       None
3    avocado
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [9]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [10]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna

<bound method Series.dropna of 0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64>

In [11]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [31]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [32]:
df

0         1         2
0  0.839392  0.536496 -0.280125
1  1.067281 -2.185732 -0.227897
2  0.846026  0.285342 -0.447249
3 -0.267729  1.276092  0.459745
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

In [33]:
df.iloc[:4, 1] = np.nan

In [34]:
df.iloc[:2, 2] = np.nan

In [35]:
df

0         1         2
0  0.839392       NaN       NaN
1  1.067281       NaN       NaN
2  0.846026       NaN -0.447249
3 -0.267729       NaN  0.459745
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

In [36]:
df.dropna()

0         1         2
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

In [37]:
df.dropna(thresh=2)

0         1         2
2  0.846026       NaN -0.447249
3 -0.267729       NaN  0.459745
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

### Filling In Missing Data

In [38]:
df.fillna(0)

0         1         2
0  0.839392  0.000000  0.000000
1  1.067281  0.000000  0.000000
2  0.846026  0.000000 -0.447249
3 -0.267729  0.000000  0.459745
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

In [39]:
df.fillna({1: 0.5, 2:0})

0         1         2
0  0.839392  0.500000  0.000000
1  1.067281  0.500000  0.000000
2  0.846026  0.500000 -0.447249
3 -0.267729  0.500000  0.459745
4 -1.244626 -0.641240 -0.328271
5 -0.357961 -2.687779  0.172878
6 -0.280329 -0.142826 -1.506812

In [40]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [41]:
df.iloc[2:, 1] = np.nan

In [42]:
df.iloc[4:, 2] = np.nan

In [43]:
df

0         1         2
0 -0.328088 -0.039434  0.127132
1 -0.363512  2.228033  0.484467
2  0.524513       NaN  0.284751
3 -0.807683       NaN  0.501101
4  0.192432       NaN       NaN
5  0.314270       NaN       NaN

In [44]:
df.fillna(method="ffill")

0         1         2
0 -0.328088 -0.039434  0.127132
1 -0.363512  2.228033  0.484467
2  0.524513  2.228033  0.284751
3 -0.807683  2.228033  0.501101
4  0.192432  2.228033  0.501101
5  0.314270  2.228033  0.501101

In [45]:
df.fillna(method="ffill", limit=2)

0         1         2
0 -0.328088 -0.039434  0.127132
1 -0.363512  2.228033  0.484467
2  0.524513  2.228033  0.284751
3 -0.807683  2.228033  0.501101
4  0.192432       NaN  0.501101
5  0.314270       NaN  0.501101

In [46]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [47]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# 7.2 Data Transformation

### Removing Duplicates

In [48]:
data = pd.DataFrame({"ki": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4,]})
data

ki  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [50]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [51]:
data.drop_duplicates()

ki  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [56]:
data["v1"] = range(7)

In [57]:
data

ki  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [72]:
#data.drop_duplicates(subset=['k1'])

In [71]:
#data.drop_duplicates(["k1", "k2"], keep="last")

### Transforming Data Using a Function or Mapping

In [84]:
data = pd.DataFrame({"food": ["bacon", "pulled pork ", "bacon", "pastrami", "corned beef", "bacon",
                             "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0         bacon     4.0
1  pulled pork      3.0
2         bacon    12.0
3      pastrami     6.0
4   corned beef     7.5
5         bacon     8.0
6      pastrami     3.0
7     honey ham     5.0
8      nova lox     6.0

In [90]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [92]:
data["animal"] = data["food"].map(meat_to_animal)

In [93]:
data

food  ounces  animal
0         bacon     4.0     pig
1  pulled pork      3.0     NaN
2         bacon    12.0     pig
3      pastrami     6.0     cow
4   corned beef     7.5     cow
5         bacon     8.0     pig
6      pastrami     3.0     cow
7     honey ham     5.0     pig
8      nova lox     6.0  salmon

In [94]:
def get_animal(x):
    return meat_to_animal[x]

In [96]:
# data["food"].map(get_animal)

### Replacing Values

In [100]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

##### Approach 1

In [98]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

##### Approach 2

In [99]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

##### Approach 3

In [101]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [104]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [106]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=["Ohio", "Colorado", "New York"],
                   columns=["one", "two", "three", "four"])

In [107]:
def transform(x):
    return x[:4].upper()

In [108]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [109]:
data.index = data.index.map(transform)

In [110]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [111]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [113]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization & Binning

In [125]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [126]:
bins = [18, 25, 35, 60, 100]

In [127]:
ages_categories = pd.cut(ages, bins)

In [128]:
ages_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [129]:
ages_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [130]:
ages_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [131]:
ages_categories.categories[0]

Interval(18, 25, closed='right')

In [136]:
# pd.value_counts(age_categories)

In [137]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [138]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [139]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [140]:
data = np.random.uniform(size=20)

In [141]:
pd.cut(data, 4, precision=2)

[(0.51, 0.75], (0.28, 0.51], (0.51, 0.75], (0.51, 0.75], (0.28, 0.51], ..., (0.28, 0.51], (0.038, 0.28], (0.28, 0.51], (0.28, 0.51], (0.038, 0.28]]
Length: 20
Categories (4, interval[float64, right]): [(0.038, 0.28] < (0.28, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [142]:
data = np.random.standard_normal(1000)

In [143]:
quartiles = pd.cut(data, 4, precision=2)
quartiles

[(1.15, 2.81], (-0.51, 1.15], (-2.16, -0.51], (-3.83, -2.16], (-0.51, 1.15], ..., (-0.51, 1.15], (1.15, 2.81], (-2.16, -0.51], (-0.51, 1.15], (-0.51, 1.15]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.83, -2.16] < (-2.16, -0.51] < (-0.51, 1.15] < (1.15, 2.81]]

In [144]:
pd.value_counts(quartiles)

(-0.51, 1.15]     592
(-2.16, -0.51]    291
(1.15, 2.81]      103
(-3.83, -2.16]     14
dtype: int64

In [145]:
pd.cut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(0.0, 0.1]     46
(0.1, 0.5]    156
(0.5, 0.9]    136
(0.9, 1.0]     28
dtype: int64

### Detecting & Filtering Outliers

In [146]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [148]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.066333     0.016662    -0.021389     0.025222
std       1.004260     1.000054     0.982892     1.025834
min      -3.078105    -3.114188    -3.373200    -3.507799
25%      -0.744146    -0.660522    -0.690219    -0.654358
50%      -0.023092     0.030645    -0.059755     0.034366
75%       0.620806     0.726840     0.654578     0.736485
max       2.968811     2.981446     3.119518     3.274374

In [149]:
col = data[2]

In [150]:
col[col.abs() > 3]

609   -3.373200
943    3.119518
Name: 2, dtype: float64

In [151]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
109  2.968811 -3.114188  0.150303 -0.530686
235  0.755175  0.763455  0.114935 -3.019895
258 -3.078105 -0.262730  1.550275 -1.207294
609 -1.499747  2.152975 -3.373200 -0.161555
626 -0.482953  0.277459 -0.921936  3.007496
635 -0.232293  0.798363  0.754499 -3.477084
810  0.488693  0.835456 -0.005825  3.274374
877  0.454657 -0.076496 -0.435912 -3.507799
925 -0.787941 -3.016845 -0.539057 -1.456501
943  0.085706 -2.118931  3.119518 -0.000522

In [152]:
data[data.abs() > 3] = np.sign(data) * 3

In [153]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.066255     0.016793    -0.021135     0.025945
std       1.004028     0.999651     0.981312     1.021767
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.744146    -0.660522    -0.690219    -0.654358
50%      -0.023092     0.030645    -0.059755     0.034366
75%       0.620806     0.726840     0.654578     0.736485
max       2.968811     2.981446     3.000000     3.000000

In [154]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0 -1.0
1 -1.0  1.0  1.0  1.0
2  1.0  1.0  1.0 -1.0
3  1.0  1.0  1.0 -1.0
4  1.0  1.0 -1.0  1.0

### Permutation & Random Sampling

In [155]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [156]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [157]:
sampler = np.random.permutation(5)
sampler

array([0, 3, 4, 2, 1])

In [158]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13

In [159]:
df.iloc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13

In [160]:
column_sampler = np.random.permutation(7)
column_sampler

array([1, 5, 6, 2, 0, 3, 4])

In [161]:
df.take(column_sampler, axis="columns")

1   5   6   2   0   3   4
0   1   5   6   2   0   3   4
1   8  12  13   9   7  10  11
2  15  19  20  16  14  17  18
3  22  26  27  23  21  24  25
4  29  33  34  30  28  31  32

In [162]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [164]:
choices = pd.Series([5, 7, -1, 6, 4])

In [165]:
choices.sample(n=10, replace=True)

4    4
0    5
2   -1
2   -1
0    5
3    6
4    4
4    4
4    4
4    4
dtype: int64

### Computing Indicator/Dummy Variables

In [166]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                  "data1": range(6)})

In [167]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [168]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [169]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [170]:
df_with_dummy = df[["data1"]].join(dummies)

In [171]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [172]:
mnames = ["movie_id", "title", "genres"]

In [173]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::", header=None, names=mnames, engine="python")

In [174]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [175]:
dummies = movies["genres"].str.get_dummies("|")

In [176]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [177]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [178]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [179]:
np.random.seed(12345)

In [182]:
values = np.random.uniform(size=10)
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [183]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [184]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           1           0           0           0           0
3           1           0           0           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           1           0

# 7.3 Extension Data Types

In [185]:
s = pd.Series([1, 2, 3, None])

In [186]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [187]:
s.dtype

dtype('float64')

In [190]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [191]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [192]:
s.dtype

Int64Dtype()

In [193]:
s[3]

<NA>

In [194]:
s[3] is pd.NA

True

In [195]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [196]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [203]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                  "B": ["one", "two", "three", "None"],
                  "C": [False, None, False, True]})

In [204]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [205]:
df["A"] = df["A"].astype("Int64")

In [206]:
df["B"] = df["B"].astype("string")

In [207]:
df["C"] = df["C"].astype("boolean")

In [208]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   None   True

# 7.4 String Manipulation

### Python Built-In String Object Methods

In [212]:
val = "a, b, guido"

In [213]:
val.split(",")

['a', ' b', ' guido']

In [214]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [215]:
first, second, third = pieces

In [216]:
first + "::" + second + "::" + third

'a::b::guido'

In [217]:
"::".join(pieces)

'a::b::guido'

In [218]:
"guido" in val

True

In [220]:
val.index(",")

1

In [221]:
val.find(":")

-1

In [222]:
# val.index(":") - It dropped an error

In [224]:
val.count(",")

2

In [225]:
val.replace(",", "::")

'a:: b:: guido'

In [226]:
val.replace(",", "::")

'a:: b:: guido'

In [227]:
val.replace(",", "")

'a b guido'

### Regular Expressions

In [3]:
text = "foo bar\ t baz \tqux"

In [5]:
re.split(r"\s+", text)

['foo', 'bar\\', 't', 'baz', 'qux']

In [6]:
regex = re.compile(r"\s+")

In [7]:
regex.split(text)

['foo', 'bar\\', 't', 'baz', 'qux']

In [8]:
regex.findall(text)

[' ', ' ', ' ', ' \t']

In [12]:
text = """ Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)


In [13]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [15]:
m = regex.search(text)
m

<re.Match object; span=(6, 21), match='dave@google.com'>

In [16]:
text[m.start():m.end()]

'dave@google.com'

In [17]:
print(regex.match(text))

None


In [18]:
print(regex.sub("REDACTED", text))

 Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [20]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+\.([A-Z]{2,4}))"

In [23]:
m = regex.match("wesm@bright.net")

In [24]:
m.groups()

()

In [25]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

### String Functions in Pandas

In [26]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
       "Rob": "rob@gmail.com", "Wes": np.nan}

In [28]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [31]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [32]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [34]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [35]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [36]:
pattern = "r([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [37]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave                     []
Steve                    []
Rob      [(ob, gmail, com)]
Wes                     NaN
dtype: object

In [38]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave                  NaN
Steve                 NaN
Rob      (ob, gmail, com)
Wes                   NaN
dtype: object

In [39]:
matches.str.get(1)

Dave       NaN
Steve      NaN
Rob      gmail
Wes        NaN
dtype: object

In [40]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [41]:
data.str.extract(pattern, flags=re.IGNORECASE)

0      1    2
Dave   NaN    NaN  NaN
Steve  NaN    NaN  NaN
Rob     ob  gmail  com
Wes    NaN    NaN  NaN

### Categorical Data

In [42]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [43]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [44]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [46]:
values = pd.Series([0, 1, 0, 0] * 2)

In [47]:
dim = pd.Series(['apple', 'orange'])

In [48]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [49]:
dim

0     apple
1    orange
dtype: object

In [50]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Categorical Extension Type in Pandas

In [4]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [5]:
N = len(fruits)

In [6]:
rng = np.random.default_rng(seed=12345)

In [7]:
df= pd.DataFrame({'fruit': fruits,
             'basket_id': np.arange(N),
             'weight': rng.uniform(0, 4, size=N)},
            columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit count    weight
0          0   apple   NaN  0.909344
1          1  orange   NaN  1.267033
2          2   apple   NaN  3.189462
3          3   apple   NaN  2.705019
4          4   apple   NaN  1.564438
5          5  orange   NaN  1.331256
6          6   apple   NaN  2.393235
7          7   apple   NaN  0.746937

In [8]:
fruit_cat = df['fruit'].astype('category')

In [9]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [13]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [14]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [15]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [16]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [17]:
df['fruit'] = df['fruit'].astype('category')

In [18]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [21]:
my_categories = pd.Categorical(['foo', 'baz', 'bar', 'foo', 'bar'])
my_categories

['foo', 'baz', 'bar', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [23]:
categories = ['foo', 'bar', 'baz']

In [24]:
codes = [0, 1, 2, 0, 0, 1]

In [28]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [29]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [30]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [31]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [32]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### Computing with Categoricals

In [33]:
rng = np.random.default_rng(seed=12345)

In [34]:
draws = rng.standard_normal(1000)

In [35]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [37]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [38]:
bins = pd.qcut(draws, 4, labels=['Q1','Q2','Q3','Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [39]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [40]:
bins = pd.Series(bins, name='quartile')

In [46]:
results = (pd.Series(draws)
          .groupby(bins)
          .agg(['count', 'min', 'max'])
          .reset_index())


In [47]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [48]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

### Better Performance with Categoricals

In [49]:
N = 10_000_000

In [50]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [51]:
categories = labels.astype('category')

In [52]:
labels.memory_usage(deep=True)

600000128

In [53]:
categories.memory_usage(deep=True)

10000540

In [54]:
%time _ =labels.astype('category')

CPU times: user 362 ms, sys: 23.1 ms, total: 385 ms
Wall time: 383 ms


In [55]:
%timeit labels.value_counts()

297 ms ± 5.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit categories.value_counts()

35.9 ms ± 547 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Categorical Methods

In [67]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [68]:
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [69]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [70]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [71]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [72]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [73]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [74]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [75]:
cat_s2.value_counts

<bound method IndexOpsMixin.value_counts of 0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']>

In [76]:
cat_s3 = cat_s[cat_s.isin(['a,', 'b'])]
cat_s3

1    b
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [77]:
cat_s3.cat.remove_unused_categories()

1    b
5    b
dtype: category
Categories (1, object): ['b']

In [78]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [79]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1