# Getting Started with Pandas

In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Introduction to pandas Data Structures

### Series

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2["a"]

-5

In [11]:
obj2["d"]

4

In [9]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    4
dtype: int64

In [10]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [17]:
obj2["a"]

-5

In [20]:
obj2["d"] = 6

In [21]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [22]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [23]:
obj * 2

0     8
1    14
2   -10
3     6
dtype: int64

In [24]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [25]:
"b" in obj2

True

In [26]:
"e" in obj2

False

In [27]:
sdata = {'Ohio':3500, 'Texas':71000, "Oregon":16000, "Utah":5000}
obj3 = pd.Series(sdata)

In [28]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj3.to_dict()

{'Ohio': 3500, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [31]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)

In [32]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
obj3 + obj4

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [39]:
obj4.name = "population"
obj.index.name = "state"

In [40]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [43]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [45]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [46]:
data = {"state": ["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
       "year": [2000, 2001, 2002, 2001, 2002, 2003],
       "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

In [47]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [48]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [49]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [50]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [51]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [54]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [53]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [58]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [59]:
frame2["debt"] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [60]:
frame2["debt"] = np.arange(6.0)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [62]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
frame2["debt"] = val

In [63]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [64]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [65]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [66]:
del frame2["eastern"]

In [67]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [68]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
              "Nevada": {2001: 2.4, 2002: 2.9}}

In [69]:
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [70]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [71]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [72]:
pdata = {"Ohio": frame3["Ohio"][:-1],
        "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [73]:
frame3.index.name = "year"
frame3.columns.name = "state"

In [74]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [75]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [76]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [77]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index

In [78]:
index

Index(['a', 'b', 'c'], dtype='object')

In [79]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
 # index[1] = "d" - it will return a TypeError

In [80]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [81]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [82]:
obj2.index is labels

True

In [83]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [84]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [85]:
"Ohio" in frame3.columns

True

In [87]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 5.2 Essential Functionality

### Reindexing

In [88]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [89]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [90]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [91]:
obj3.reindex(np.arange(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [92]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [93]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [94]:
states = ["Texas", "Utah", "California"]

In [95]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [96]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [97]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

### Dropping Entries from an Axis

In [11]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [12]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [13]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [14]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [17]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [18]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, Selection & Filtering

In [19]:
obj = pd.Series(np.arange(4.), index=["a","b","c","d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [20]:
obj["b"]

1.0

In [117]:
obj[1]

1.0

In [118]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [119]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [120]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [121]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [122]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [21]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [22]:
obj1

2    1
0    2
1    3
dtype: int64

In [23]:
obj2

a    1
b    2
c    3
dtype: int64

In [126]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [127]:
obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [128]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [129]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [134]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [24]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [156]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [157]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [158]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [159]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [26]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection on DataFrame with loc & iloc

In [27]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [29]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [30]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [31]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [32]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [169]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [33]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [34]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [35]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [36]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Integer Indexing pitfalls

In [37]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [177]:
# ser[-1]

In [38]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [39]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

2.0

In [40]:
ser.iloc[-1]

2.0

In [41]:
ser[:2]

0    0.0
1    1.0
dtype: float64

### Pitfalls with Chained Indexing

In [42]:
data.loc[:, "one"] = 1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [44]:
data.iloc[2] = 5
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [46]:
data.loc[data["four"]> 5] = 3
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [47]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [48]:
data.loc[data.three == 5, "three"] = 6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

### Arithmetic & Data Alignment

In [49]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [50]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [51]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [52]:
s1 + s1

a    14.6
c    -5.0
d     6.8
e     3.0
dtype: float64

In [58]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bde"), index=["Ohio", "Texas", "Colorado"])
df1

b    d    e
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [63]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah","Ohio", "Texas", "Colorado"])
df2

b     d     e
Utah      0.0   1.0   2.0
Ohio      3.0   4.0   5.0
Texas     6.0   7.0   8.0
Colorado  9.0  10.0  11.0

In [64]:
df1 + df2

b     d     e
Colorado  15.0  17.0  19.0
Ohio       3.0   5.0   7.0
Texas      9.0  11.0  13.0
Utah       NaN   NaN   NaN

In [65]:
df1 = pd.DataFrame({"A": [1, 2]})
df1

A
0  1
1  2

In [66]:
df2 = pd.DataFrame({"B": [3, 4]})
df2

B
0  3
1  4

In [67]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic Methods with Fill Values

In [76]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))

In [77]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

In [78]:
df2.loc[1, "b"] = np.nan

In [79]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [80]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [81]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [88]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [89]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [90]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [91]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame & Series

In [92]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [93]:
arr[0]

array([0., 1., 2., 3.])

In [94]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [95]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah","Ohio","Texas","Oregon"])

In [96]:
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [98]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [99]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [100]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [102]:
series3 = frame["d"]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [103]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [104]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application & Mapping

In [105]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah    0.781575 -1.601492  0.149183
Ohio    0.130045 -0.140437 -0.471530
Texas   0.422358 -0.512085  0.208059
Oregon  0.382411  0.579097 -1.280164

In [106]:
np.abs(frame)

b         d         e
Utah    0.781575  1.601492  0.149183
Ohio    0.130045  0.140437  0.471530
Texas   0.422358  0.512085  0.208059
Oregon  0.382411  0.579097  1.280164

In [107]:
def f1(x):
    return x.max() - x.min()

In [108]:
frame.apply(f1)

b    0.651530
d    2.180590
e    1.488223
dtype: float64

In [109]:
frame.apply(f1, axis="columns")

Utah      2.383068
Ohio      0.601575
Texas     0.934444
Oregon    1.859262
dtype: float64

In [110]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [111]:
frame.apply(f2)

b         d         e
min  0.130045 -1.601492 -1.280164
max  0.781575  0.579097  0.208059

In [113]:
def my_format(x):
    return f"{x: .2f}"

In [114]:
frame.applymap(my_format)

b      d      e
Utah     0.78  -1.60   0.15
Ohio     0.13  -0.14  -0.47
Texas    0.42  -0.51   0.21
Oregon   0.38   0.58  -1.28

In [115]:
frame["e"].map(my_format)

Utah       0.15
Ohio      -0.47
Texas      0.21
Oregon    -1.28
Name: e, dtype: object

### Sorting & Ranking

In [116]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [117]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [118]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"],
                    columns=["d", "a", "b", "c"])

In [119]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [120]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [121]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [123]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [124]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [126]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [127]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [128]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [129]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [130]:
frame.sort_values(["a","b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [131]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 2])
obj.rank()

0    6.5
1    1.0
2    6.5
3    5.0
4    3.5
5    2.0
6    3.5
dtype: float64

In [132]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [133]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.0
4    4.5
5    6.0
6    4.5
dtype: float64

In [135]:
frame = pd.DataFrame({"b": [ 4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [136]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [138]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [139]:
obj.index.is_unique

False

In [140]:
obj["a"]

a    0
a    1
dtype: int64

In [141]:
obj["c"]

4

In [143]:
df = pd.DataFrame(np.random.standard_normal((5, 3)), index=["a", "a", "b", "b", "c"])
df

0         1         2
a  0.263725  0.361591  1.091780
a -0.772675  0.352499  1.566832
b -1.456899  0.908726 -0.226427
b -0.376613 -0.256384 -0.635943
c  1.267717 -1.943019  0.834059

In [144]:
df.loc["b"]

0         1         2
b -1.456899  0.908726 -0.226427
b -0.376613 -0.256384 -0.635943

In [145]:
df.loc["c"]

0    1.267717
1   -1.943019
2    0.834059
Name: c, dtype: float64

# 5.3 Summarizing & Computing Descriptive Statistics

In [146]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index=["a", "b", "c", "d"],
                 columns=["one", "two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [147]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [148]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [149]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [150]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [153]:
df.idxmax()

one    b
two    d
dtype: object

In [154]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [155]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [156]:
obj = pd.Series(["a", "a", "b", "c"] * 4)


In [157]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [164]:
price = pd.read_pickle("examples/yahoo_price.pkl")

In [165]:
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [166]:
returns = price.pct_change()

In [167]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [168]:
returns["MSFT"].corr(returns["IBM"])

0.49976361144151144

In [170]:
returns["MSFT"].cov(returns["IBM"])

8.870655479703546e-05

In [171]:
returns["MSFT"].corr(returns["IBM"])

0.49976361144151144

In [172]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [173]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [174]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [175]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### Unique Values, Values Counts & Membership

In [176]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [177]:
uniques = obj.unique()

In [178]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [179]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [180]:
pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [181]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [182]:
mask = obj.isin(["b", "c"])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [183]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [185]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)

In [187]:
indices

array([0, 2, 1, 1, 0, 2])

In [188]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                    "Qu2": [2, 3, 1, 2, 3],
                    "Qu3": [1, 5, 2, 4, 4],})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [189]:
data["Qu1"].value_counts().sort_index()

1    1
3    2
4    2
Name: Qu1, dtype: int64

In [190]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [191]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [192]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
dtype: int64